# Generated by Django 4.1.5 on 2023-01-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postcomment_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
